-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."ReportePlaga_reporteplaga"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    fecha_reporte timestamp with time zone NOT NULL,
    observaciones text COLLATE pg_catalog."default" NOT NULL,
    estado character varying(2) COLLATE pg_catalog."default" NOT NULL,
    bancal_id bigint NOT NULL,
    plaga_id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    CONSTRAINT "ReportePlaga_reporteplaga_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.actividades_actividad
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    descripcion text COLLATE pg_catalog."default" NOT NULL,
    fecha_inicio timestamp with time zone NOT NULL,
    fecha_fin timestamp with time zone NOT NULL,
    cultivo_id bigint NOT NULL,
    tipo_actividad_id bigint NOT NULL,
    estado character varying(20) COLLATE pg_catalog."default" NOT NULL,
    instrucciones_adicionales text COLLATE pg_catalog."default",
    prioridad character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT actividades_actividad_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.actividades_actividad_usuarios
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    actividad_id bigint NOT NULL,
    usuarios_id bigint NOT NULL,
    CONSTRAINT actividades_actividad_usuarios_pkey PRIMARY KEY (id),
    CONSTRAINT actividades_actividad_us_actividad_id_usuarios_id_5bb8c505_uniq UNIQUE (actividad_id, usuarios_id)
);

CREATE TABLE IF NOT EXISTS public.actividades_prestamoherramienta
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    entregada boolean NOT NULL,
    devuelta boolean NOT NULL,
    fecha_devolucion timestamp with time zone,
    actividad_id bigint NOT NULL,
    herramienta_id integer NOT NULL,
    bodega_herramienta_id integer,
    cantidad_devuelta integer NOT NULL,
    cantidad_entregada integer NOT NULL,
    CONSTRAINT actividades_prestamoherramienta_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.actividades_prestamoinsumo
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cantidad_usada integer NOT NULL,
    cantidad_devuelta integer NOT NULL,
    fecha_devolucion timestamp with time zone,
    actividad_id bigint NOT NULL,
    insumo_id integer NOT NULL,
    unidad_medida_id integer,
    CONSTRAINT actividades_prestamoinsumo_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.afecciones_afeccion
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(30) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default" NOT NULL,
    fecha_deteccion date NOT NULL,
    estado character varying(2) COLLATE pg_catalog."default" NOT NULL,
    plaga_id bigint NOT NULL,
    bancal_id bigint NOT NULL,
    cultivo_id bigint NOT NULL,
    gravedad character varying(1) COLLATE pg_catalog."default" NOT NULL,
    reporte_id bigint,
    CONSTRAINT afecciones_afeccion_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.auth_group
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_group_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.auth_group_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.auth_permission
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
    CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename)
);

CREATE TABLE IF NOT EXISTS public.bancal_bancal
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(15) COLLATE pg_catalog."default" NOT NULL,
    lote_id bigint NOT NULL,
    latitud numeric(9, 6),
    longitud numeric(9, 6),
    tam_x numeric(5, 2),
    tam_y numeric(5, 2),
    CONSTRAINT bancal_bancal_pkey PRIMARY KEY (id),
    CONSTRAINT bancal_bancal_nombre_2c7867a5_uniq UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.bodega_bodega
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(50) COLLATE pg_catalog."default" NOT NULL,
    activo boolean NOT NULL,
    capacidad integer NOT NULL,
    ubicacion character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT bodega_bodega_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.bodega_herramienta_bodegaherramienta
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cantidad integer NOT NULL,
    bodega_id integer NOT NULL,
    herramienta_id integer NOT NULL,
    costo_total numeric(10, 2) NOT NULL,
    creador_id bigint,
    cantidad_prestada integer NOT NULL,
    CONSTRAINT bodega_herramienta_bodegaherramienta_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.bodega_insumo_bodegainsumo
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cantidad integer NOT NULL,
    bodega_id integer NOT NULL,
    insumo_id integer NOT NULL,
    CONSTRAINT bodega_insumo_bodegainsumo_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.bodega_precio_producto_bodegaprecioproducto
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    precio numeric(10, 2) NOT NULL,
    bodega_id integer NOT NULL,
    creador_id bigint,
    producto_id bigint NOT NULL,
    cantidad integer NOT NULL,
    CONSTRAINT bodega_precio_producto_bodegaprecioproducto_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.controles_control
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    descripcion text COLLATE pg_catalog."default" NOT NULL,
    fecha_control date NOT NULL,
    afeccion_id bigint NOT NULL,
    producto_id integer NOT NULL,
    tipo_control_id bigint NOT NULL,
    efectividad smallint NOT NULL,
    observaciones text COLLATE pg_catalog."default" NOT NULL,
    responsable_id bigint,
    CONSTRAINT controles_control_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.cosechas_cosecha
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cantidad integer NOT NULL,
    unidades_de_medida_id integer NOT NULL,
    fecha date NOT NULL,
    id_cultivo_id bigint NOT NULL,
    CONSTRAINT cosechas_cosecha_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.costo_beneficio_analisiscostobeneficio
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    fecha_calculo timestamp with time zone NOT NULL,
    mano_obra numeric(12, 2) NOT NULL,
    insumos numeric(12, 2) NOT NULL,
    total_costos numeric(12, 2) NOT NULL,
    total_ingresos numeric(12, 2) NOT NULL,
    rentabilidad numeric(12, 2) NOT NULL,
    roi numeric(8, 2) NOT NULL,
    cosecha_id bigint NOT NULL,
    CONSTRAINT costo_beneficio_analisiscostobeneficio_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.cultivos_cultivo
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    unidad_de_medida_id integer NOT NULL,
    activo boolean NOT NULL,
    "fechaSiembra" date NOT NULL,
    "Bancal_id" bigint NOT NULL,
    "Especie_id" bigint NOT NULL,
    CONSTRAINT cultivos_cultivo_pkey PRIMARY KEY (id),
    CONSTRAINT cultivos_cultivo_nombre_bc18fa63_uniq UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.datos_meteorologicos_datos_metereologicos
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    fecha_medicion timestamp with time zone NOT NULL,
    fk_bancal_id bigint,
    fk_sensor_id bigint,
    humedad_ambiente numeric(10, 2),
    temperatura numeric(10, 2),
    luminosidad numeric(10, 2),
    humedad_suelo numeric(5, 2),
    lluvia numeric(5, 2),
    ph_suelo numeric(4, 2),
    direccion_viento numeric(3, 0),
    velocidad_viento numeric(5, 2),
    CONSTRAINT datos_meteorologicos_datos_metereologicos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.datos_meteorologicos_datoshistoricos
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    temperatura numeric(10, 2),
    humedad_ambiente numeric(10, 2),
    luminosidad numeric(10, 2),
    lluvia numeric(5, 2),
    velocidad_viento numeric(5, 2),
    direccion_viento numeric(3, 0),
    humedad_suelo numeric(5, 2),
    ph_suelo numeric(4, 2),
    fecha_promedio timestamp with time zone NOT NULL,
    cantidad_mediciones integer NOT NULL,
    fk_bancal_id bigint,
    fk_sensor_id bigint,
    CONSTRAINT datos_meteorologicos_datoshistoricos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_admin_log
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    action_time timestamp with time zone NOT NULL,
    object_id text COLLATE pg_catalog."default",
    object_repr character varying(200) COLLATE pg_catalog."default" NOT NULL,
    action_flag smallint NOT NULL,
    change_message text COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_content_type
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    app_label character varying(100) COLLATE pg_catalog."default" NOT NULL,
    model character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_content_type_pkey PRIMARY KEY (id),
    CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model)
);

CREATE TABLE IF NOT EXISTS public.django_migrations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    app character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    applied timestamp with time zone NOT NULL,
    CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_session
(
    session_key character varying(40) COLLATE pg_catalog."default" NOT NULL,
    session_data text COLLATE pg_catalog."default" NOT NULL,
    expire_date timestamp with time zone NOT NULL,
    CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);

CREATE TABLE IF NOT EXISTS public.especies_especie
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(30) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default" NOT NULL,
    "largoCrecimiento" integer NOT NULL,
    img character varying(100) COLLATE pg_catalog."default",
    fk_tipo_especie_id bigint NOT NULL,
    CONSTRAINT especies_especie_pkey PRIMARY KEY (id),
    CONSTRAINT especies_especie_nombre_b025edc5_uniq UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.evapotranspiracion_evapotranspiracion
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    fecha date NOT NULL,
    valor numeric(5, 2) NOT NULL,
    creado timestamp with time zone NOT NULL,
    fk_bancal_id bigint,
    CONSTRAINT evapotranspiracion_evapotranspiracion_pkey PRIMARY KEY (id),
    CONSTRAINT evapotranspiracion_evapo_fk_bancal_id_fecha_e3bb5a14_uniq UNIQUE (fk_bancal_id, fecha)
);

CREATE TABLE IF NOT EXISTS public.herramientas_herramienta
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default" NOT NULL,
    cantidad integer NOT NULL,
    estado character varying(50) COLLATE pg_catalog."default" NOT NULL,
    activo boolean NOT NULL,
    fecha_registro timestamp with time zone NOT NULL,
    precio numeric(10, 0) NOT NULL,
    CONSTRAINT herramientas_herramienta_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.insumos_insumo
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default" NOT NULL,
    cantidad integer NOT NULL,
    activo boolean NOT NULL,
    fecha_caducidad date,
    fecha_registro timestamp with time zone NOT NULL,
    tipo_empacado character varying(100) COLLATE pg_catalog."default",
    precio_insumo numeric(10, 2) NOT NULL,
    unidad_medida_id integer,
    tipo_insumo_id integer,
    CONSTRAINT insumos_insumo_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.insumos_tiposinsumo
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    creada_por_usuario boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    CONSTRAINT insumos_tiposinsumo_pkey PRIMARY KEY (id),
    CONSTRAINT insumos_tiposinsumo_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.lotes_lote
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(15) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    activo boolean NOT NULL,
    tam_x numeric(5, 2) NOT NULL,
    tam_y numeric(5, 2) NOT NULL,
    latitud numeric(9, 6) NOT NULL,
    longitud numeric(9, 6) NOT NULL,
    CONSTRAINT lotes_lote_pkey PRIMARY KEY (id),
    CONSTRAINT lotes_lote_nombre_4e09c340_uniq UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.mapa_puntomapa
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    latitud numeric(9, 6) NOT NULL,
    longitud numeric(9, 6) NOT NULL,
    creado timestamp with time zone NOT NULL DEFAULT now(),
    descripcion text COLLATE pg_catalog."default",
    usuario_id integer,
    cultivo_id integer,
    CONSTRAINT mapa_puntomapa_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pagos_pago
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    fecha_calculo timestamp with time zone NOT NULL,
    fecha_fin date NOT NULL,
    fecha_inicio date NOT NULL,
    horas_trabajadas numeric(10, 2) NOT NULL,
    jornales numeric(10, 2) NOT NULL,
    salario_id bigint NOT NULL,
    total_pago numeric(10, 2) NOT NULL,
    usuario_id bigint NOT NULL,
    CONSTRAINT pagos_pago_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pagos_pago_actividades
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    pago_id bigint NOT NULL,
    actividad_id bigint NOT NULL,
    CONSTRAINT pagos_pago_actividades_pkey PRIMARY KEY (id),
    CONSTRAINT pagos_pago_actividades_pago_id_actividad_id_9dc80d27_uniq UNIQUE (pago_id, actividad_id)
);

CREATE TABLE IF NOT EXISTS public.plagas_plaga
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(30) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default" NOT NULL,
    img character varying(100) COLLATE pg_catalog."default",
    fk_tipo_plaga_id bigint NOT NULL,
    CONSTRAINT plagas_plaga_pkey PRIMARY KEY (id),
    CONSTRAINT plagas_plaga_nombre_4f9e0d02_uniq UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.plantaciones_plantacion
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    bancal_id bigint NOT NULL,
    id_cultivo_id bigint NOT NULL,
    CONSTRAINT plantaciones_plantacion_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.precios_productos_precio_producto
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    precio numeric(10, 2) NOT NULL,
    fecha_registro date NOT NULL,
    "Producto_id" bigint,
    fecha_caducidad date,
    stock integer NOT NULL,
    unidad_medida_id integer,
    CONSTRAINT precio_producto_precioproducto_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.residuos_residuo
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(30) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    fecha date NOT NULL,
    cantidad integer NOT NULL,
    id_tipo_residuo_id bigint NOT NULL,
    id_cosecha_id bigint NOT NULL,
    CONSTRAINT residuos_residuo_pkey PRIMARY KEY (id),
    CONSTRAINT residuos_residuo_nombre_5cc948fd_uniq UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.roles_roles
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(20) COLLATE pg_catalog."default" NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_actualizacion timestamp with time zone NOT NULL,
    CONSTRAINT roles_roles_pkey PRIMARY KEY (id),
    CONSTRAINT roles_roles_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.salario_salario
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "valorJornal" numeric(10, 2) NOT NULL,
    fecha_de_implementacion date NOT NULL,
    rol_id bigint NOT NULL,
    activo boolean NOT NULL,
    CONSTRAINT salario_salario_pkey PRIMARY KEY (id),
    CONSTRAINT salario_salario_rol_id_fecha_de_implementacion_395edc5f_uniq UNIQUE (rol_id, fecha_de_implementacion)
);

CREATE TABLE IF NOT EXISTS public.semillero_semillero
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    unidades_de_medida integer NOT NULL,
    "fechaSiembra" date NOT NULL,
    "fechaEstimada" date NOT NULL,
    img character varying(100) COLLATE pg_catalog."default",
    fk_especie_id bigint NOT NULL,
    CONSTRAINT semillero_semillero_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sensores_sensor
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    tipo_sensor_id bigint NOT NULL,
    descripcion text COLLATE pg_catalog."default" NOT NULL,
    estado character varying(10) COLLATE pg_catalog."default" NOT NULL,
    bancal_id bigint,
    device_code character varying(100) COLLATE pg_catalog."default",
    medida_maxima numeric(10, 2) NOT NULL,
    medida_minima numeric(10, 2) NOT NULL,
    CONSTRAINT sensores_sensor_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sensores_tiposensor
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    unidad_medida character varying(10) COLLATE pg_catalog."default" NOT NULL,
    medida_minima numeric(10, 2) NOT NULL,
    medida_maxima numeric(10, 2) NOT NULL,
    descripcion text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT sensores_tiposensor_pkey PRIMARY KEY (id),
    CONSTRAINT sensores_tiposensor_nombre_b7573ecc_uniq UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.tipo_actividad_tipoactividad
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tipo_actividad_tipoactividad_pkey PRIMARY KEY (id),
    CONSTRAINT tipo_actividad_tipoactividad_nombre_43402eb9_uniq UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.tipo_control_tipocontrol
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(30) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tipo_control_tipocontrol_pkey PRIMARY KEY (id),
    CONSTRAINT tipo_control_tipocontrol_nombre_f51ec0a5_uniq UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.tipo_especies_tipoespecie
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(30) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default" NOT NULL,
    img character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT tipo_especies_tipoespecie_pkey PRIMARY KEY (id),
    CONSTRAINT tipo_especies_tipoespecie_nombre_78b5210b_uniq UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.tipo_plaga_tipoplaga
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(30) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default" NOT NULL,
    img character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT tipo_plaga_tipoplaga_pkey PRIMARY KEY (id),
    CONSTRAINT tipo_plaga_tipoplaga_nombre_b6481a0c_uniq UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.tipos_residuos_tiporesiduo
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(30) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    CONSTRAINT tipos_residuos_tiporesiduo_pkey PRIMARY KEY (id),
    CONSTRAINT tipos_residuos_tiporesiduo_nombre_0376d577_uniq UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.unidad_medida_unidadmedida
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    creada_por_usuario boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    CONSTRAINT unidad_medida_unidadmedida_pkey PRIMARY KEY (id),
    CONSTRAINT unidad_medida_unidadmedida_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.usuarios_passwordresettoken
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    token character varying(32) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT usuarios_passwordresettoken_pkey PRIMARY KEY (id),
    CONSTRAINT usuarios_passwordresettoken_token_key UNIQUE (token)
);

CREATE TABLE IF NOT EXISTS public.usuarios_usuarios
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    password character varying(128) COLLATE pg_catalog."default" NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    is_staff boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    nombre character varying(30) COLLATE pg_catalog."default" NOT NULL,
    apellido character varying(30) COLLATE pg_catalog."default" NOT NULL,
    email character varying(254) COLLATE pg_catalog."default",
    numero_documento integer,
    is_active boolean NOT NULL,
    rol_id bigint,
    CONSTRAINT usuarios_usuarios_pkey PRIMARY KEY (id),
    CONSTRAINT usuarios_usuarios_email_key UNIQUE (email),
    CONSTRAINT usuarios_usuarios_numero_documento_key UNIQUE (numero_documento),
    CONSTRAINT usuarios_usuarios_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.usuarios_usuarios_groups
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    usuarios_id bigint NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT usuarios_usuarios_groups_pkey PRIMARY KEY (id),
    CONSTRAINT usuarios_usuarios_groups_usuarios_id_group_id_31056d4d_uniq UNIQUE (usuarios_id, group_id)
);

CREATE TABLE IF NOT EXISTS public.usuarios_usuarios_user_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    usuarios_id bigint NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT usuarios_usuarios_user_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT usuarios_usuarios_user_p_usuarios_id_permission_i_1fb72da5_uniq UNIQUE (usuarios_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.venta_detalleventa
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cantidad integer NOT NULL,
    total numeric(10, 2) NOT NULL,
    producto_id bigint NOT NULL,
    unidades_de_medida_id integer NOT NULL,
    venta_id bigint NOT NULL,
    CONSTRAINT venta_detalleventa_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.venta_venta
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    fecha timestamp with time zone NOT NULL,
    cambio numeric(10, 2) NOT NULL,
    monto_entregado numeric(10, 2) NOT NULL,
    CONSTRAINT venta_venta_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."ReportePlaga_reporteplaga"
    ADD CONSTRAINT "ReportePlaga_reporte_bancal_id_f333b1fe_fk_bancal_ba" FOREIGN KEY (bancal_id)
    REFERENCES public.bancal_bancal (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "ReportePlaga_reporteplaga_lote_id_f58800de"
    ON public."ReportePlaga_reporteplaga"(bancal_id);


ALTER TABLE IF EXISTS public."ReportePlaga_reporteplaga"
    ADD CONSTRAINT "ReportePlaga_reporte_usuario_id_a18220d3_fk_usuarios_" FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios_usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "ReportePlaga_reporteplaga_usuario_id_a18220d3"
    ON public."ReportePlaga_reporteplaga"(usuario_id);


ALTER TABLE IF EXISTS public."ReportePlaga_reporteplaga"
    ADD CONSTRAINT "ReportePlaga_reporteplaga_plaga_id_cfc6a6be_fk_plagas_plaga_id" FOREIGN KEY (plaga_id)
    REFERENCES public.plagas_plaga (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "ReportePlaga_reporteplaga_plaga_id_cfc6a6be"
    ON public."ReportePlaga_reporteplaga"(plaga_id);


ALTER TABLE IF EXISTS public.actividades_actividad
    ADD CONSTRAINT actividades_activida_cultivo_id_8ae22c07_fk_cultivos_ FOREIGN KEY (cultivo_id)
    REFERENCES public.cultivos_cultivo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS actividades_actividad_cultivo_id_8ae22c07
    ON public.actividades_actividad(cultivo_id);


ALTER TABLE IF EXISTS public.actividades_actividad
    ADD CONSTRAINT actividades_activida_tipo_actividad_id_84c91e30_fk_tipo_acti FOREIGN KEY (tipo_actividad_id)
    REFERENCES public.tipo_actividad_tipoactividad (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS actividades_actividad_tipo_actividad_id_84c91e30
    ON public.actividades_actividad(tipo_actividad_id);


ALTER TABLE IF EXISTS public.actividades_actividad_usuarios
    ADD CONSTRAINT actividades_activida_actividad_id_2510a227_fk_actividad FOREIGN KEY (actividad_id)
    REFERENCES public.actividades_actividad (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS actividades_actividad_usuarios_actividad_id_2510a227
    ON public.actividades_actividad_usuarios(actividad_id);


ALTER TABLE IF EXISTS public.actividades_actividad_usuarios
    ADD CONSTRAINT actividades_activida_usuarios_id_365290f9_fk_usuarios_ FOREIGN KEY (usuarios_id)
    REFERENCES public.usuarios_usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS actividades_actividad_usuarios_usuarios_id_365290f9
    ON public.actividades_actividad_usuarios(usuarios_id);


ALTER TABLE IF EXISTS public.actividades_prestamoherramienta
    ADD CONSTRAINT actividades_prestamo_actividad_id_61069813_fk_actividad FOREIGN KEY (actividad_id)
    REFERENCES public.actividades_actividad (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS actividades_prestamoherramienta_actividad_id_61069813
    ON public.actividades_prestamoherramienta(actividad_id);


ALTER TABLE IF EXISTS public.actividades_prestamoherramienta
    ADD CONSTRAINT actividades_prestamo_bodega_herramienta_i_3f6f1782_fk_bodega_he FOREIGN KEY (bodega_herramienta_id)
    REFERENCES public.bodega_herramienta_bodegaherramienta (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS actividades_prestamoherramienta_bodega_herramienta_id_3f6f1782
    ON public.actividades_prestamoherramienta(bodega_herramienta_id);


ALTER TABLE IF EXISTS public.actividades_prestamoherramienta
    ADD CONSTRAINT actividades_prestamo_herramienta_id_36d0477e_fk_herramien FOREIGN KEY (herramienta_id)
    REFERENCES public.herramientas_herramienta (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS actividades_prestamoherramienta_herramienta_id_36d0477e
    ON public.actividades_prestamoherramienta(herramienta_id);


ALTER TABLE IF EXISTS public.actividades_prestamoinsumo
    ADD CONSTRAINT actividades_prestamo_actividad_id_5f879626_fk_actividad FOREIGN KEY (actividad_id)
    REFERENCES public.actividades_actividad (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS actividades_prestamoinsumo_actividad_id_5f879626
    ON public.actividades_prestamoinsumo(actividad_id);


ALTER TABLE IF EXISTS public.actividades_prestamoinsumo
    ADD CONSTRAINT actividades_prestamo_insumo_id_e71190b8_fk_insumos_i FOREIGN KEY (insumo_id)
    REFERENCES public.insumos_insumo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS actividades_prestamoinsumo_insumo_id_e71190b8
    ON public.actividades_prestamoinsumo(insumo_id);


ALTER TABLE IF EXISTS public.actividades_prestamoinsumo
    ADD CONSTRAINT actividades_prestamo_unidad_medida_id_8ca52519_fk_unidad_me FOREIGN KEY (unidad_medida_id)
    REFERENCES public.unidad_medida_unidadmedida (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS actividades_prestamoinsumo_unidad_medida_id_8ca52519
    ON public.actividades_prestamoinsumo(unidad_medida_id);


ALTER TABLE IF EXISTS public.afecciones_afeccion
    ADD CONSTRAINT afecciones_afeccion_bancal_id_9eaa6ca4_fk_bancal_bancal_id FOREIGN KEY (bancal_id)
    REFERENCES public.bancal_bancal (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "afecciones_afeccion_Bancal_id_1e0ca991"
    ON public.afecciones_afeccion(bancal_id);


ALTER TABLE IF EXISTS public.afecciones_afeccion
    ADD CONSTRAINT afecciones_afeccion_cultivo_id_e3811212_fk_cultivos_cultivo_id FOREIGN KEY (cultivo_id)
    REFERENCES public.cultivos_cultivo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS afecciones_afeccion_cultivo_id_e3811212
    ON public.afecciones_afeccion(cultivo_id);


ALTER TABLE IF EXISTS public.afecciones_afeccion
    ADD CONSTRAINT afecciones_afeccion_plaga_id_9b43e1ed_fk_plagas_plaga_id FOREIGN KEY (plaga_id)
    REFERENCES public.plagas_plaga (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS afecciones_afeccion_id_plaga_id_40c416ee
    ON public.afecciones_afeccion(plaga_id);


ALTER TABLE IF EXISTS public.afecciones_afeccion
    ADD CONSTRAINT "afecciones_afeccion_reporte_id_4561e8f9_fk_ReportePl" FOREIGN KEY (reporte_id)
    REFERENCES public."ReportePlaga_reporteplaga" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS afecciones_afeccion_reporte_id_4561e8f9
    ON public.afecciones_afeccion(reporte_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_permission_id_84c5c92e
    ON public.auth_group_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_group_id_b120cbf9
    ON public.auth_group_permissions(group_id);


ALTER TABLE IF EXISTS public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_permission_content_type_id_2f476e4b
    ON public.auth_permission(content_type_id);


ALTER TABLE IF EXISTS public.bancal_bancal
    ADD CONSTRAINT bancal_bancal_lote_id_7cca0e3d_fk_lotes_lote_id FOREIGN KEY (lote_id)
    REFERENCES public.lotes_lote (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS bancal_bancal_lote_id_7cca0e3d
    ON public.bancal_bancal(lote_id);


ALTER TABLE IF EXISTS public.bodega_herramienta_bodegaherramienta
    ADD CONSTRAINT bodega_herramienta_b_bodega_id_adf402a4_fk_bodega_bo FOREIGN KEY (bodega_id)
    REFERENCES public.bodega_bodega (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS bodega_herramienta_bodegaherramienta_bodega_id_adf402a4
    ON public.bodega_herramienta_bodegaherramienta(bodega_id);


ALTER TABLE IF EXISTS public.bodega_herramienta_bodegaherramienta
    ADD CONSTRAINT bodega_herramienta_b_creador_id_6040983e_fk_usuarios_ FOREIGN KEY (creador_id)
    REFERENCES public.usuarios_usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS bodega_herramienta_bodegaherramienta_creador_id_6040983e
    ON public.bodega_herramienta_bodegaherramienta(creador_id);


ALTER TABLE IF EXISTS public.bodega_herramienta_bodegaherramienta
    ADD CONSTRAINT bodega_herramienta_b_herramienta_id_51aff9e5_fk_herramien FOREIGN KEY (herramienta_id)
    REFERENCES public.herramientas_herramienta (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS bodega_herramienta_bodegaherramienta_herramienta_id_51aff9e5
    ON public.bodega_herramienta_bodegaherramienta(herramienta_id);


ALTER TABLE IF EXISTS public.bodega_insumo_bodegainsumo
    ADD CONSTRAINT bodega_insumo_bodega_bodega_id_6c8b2271_fk_bodega_bo FOREIGN KEY (bodega_id)
    REFERENCES public.bodega_bodega (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS bodega_insumo_bodegainsumo_bodega_id_6c8b2271
    ON public.bodega_insumo_bodegainsumo(bodega_id);


ALTER TABLE IF EXISTS public.bodega_insumo_bodegainsumo
    ADD CONSTRAINT bodega_insumo_bodega_insumo_id_88897511_fk_insumos_i FOREIGN KEY (insumo_id)
    REFERENCES public.insumos_insumo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS bodega_insumo_bodegainsumo_insumo_id_88897511
    ON public.bodega_insumo_bodegainsumo(insumo_id);


ALTER TABLE IF EXISTS public.bodega_precio_producto_bodegaprecioproducto
    ADD CONSTRAINT bodega_precio_produc_bodega_id_f9fa70f7_fk_bodega_bo FOREIGN KEY (bodega_id)
    REFERENCES public.bodega_bodega (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS bodega_precio_producto_bodegaprecioproducto_bodega_id_f9fa70f7
    ON public.bodega_precio_producto_bodegaprecioproducto(bodega_id);


ALTER TABLE IF EXISTS public.bodega_precio_producto_bodegaprecioproducto
    ADD CONSTRAINT bodega_precio_produc_creador_id_6efff5bd_fk_usuarios_ FOREIGN KEY (creador_id)
    REFERENCES public.usuarios_usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS bodega_precio_producto_bodegaprecioproducto_creador_id_6efff5bd
    ON public.bodega_precio_producto_bodegaprecioproducto(creador_id);


ALTER TABLE IF EXISTS public.bodega_precio_producto_bodegaprecioproducto
    ADD CONSTRAINT bodega_precio_produc_producto_id_2d0e18e3_fk_precios_p FOREIGN KEY (producto_id)
    REFERENCES public.precios_productos_precio_producto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS bodega_precio_producto_bod_producto_id_2d0e18e3
    ON public.bodega_precio_producto_bodegaprecioproducto(producto_id);


ALTER TABLE IF EXISTS public.controles_control
    ADD CONSTRAINT controles_control_afeccion_id_eb223cf3_fk_afeccione FOREIGN KEY (afeccion_id)
    REFERENCES public.afecciones_afeccion (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS controles_control_id_afeccion_id_a54cc5ab
    ON public.controles_control(afeccion_id);


ALTER TABLE IF EXISTS public.controles_control
    ADD CONSTRAINT controles_control_producto_id_fc80f2c8_fk_insumos_insumo_id FOREIGN KEY (producto_id)
    REFERENCES public.insumos_insumo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS controles_control_id_producto_id_bc819fd6
    ON public.controles_control(producto_id);


ALTER TABLE IF EXISTS public.controles_control
    ADD CONSTRAINT controles_control_responsable_id_31a027cf_fk_usuarios_ FOREIGN KEY (responsable_id)
    REFERENCES public.usuarios_usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS controles_control_responsable_id_31a027cf
    ON public.controles_control(responsable_id);


ALTER TABLE IF EXISTS public.controles_control
    ADD CONSTRAINT controles_control_tipo_control_id_6ce7082b_fk_tipo_cont FOREIGN KEY (tipo_control_id)
    REFERENCES public.tipo_control_tipocontrol (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "controles_control_id_tipoControl_id_a0b8ec63"
    ON public.controles_control(tipo_control_id);


ALTER TABLE IF EXISTS public.cosechas_cosecha
    ADD CONSTRAINT cosechas_cosecha_id_cultivo_id_c9f33fa9_fk_cultivos_cultivo_id FOREIGN KEY (id_cultivo_id)
    REFERENCES public.cultivos_cultivo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS cosechas_cosecha_id_cultivo_id_c9f33fa9
    ON public.cosechas_cosecha(id_cultivo_id);


ALTER TABLE IF EXISTS public.cosechas_cosecha
    ADD CONSTRAINT cosechas_cosecha_unidades_de_medida_i_28b88f77_fk_unidad_me FOREIGN KEY (unidades_de_medida_id)
    REFERENCES public.unidad_medida_unidadmedida (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS cosechas_cosecha_unidades_de_medida_id_28b88f77
    ON public.cosechas_cosecha(unidades_de_medida_id);


ALTER TABLE IF EXISTS public.costo_beneficio_analisiscostobeneficio
    ADD CONSTRAINT costo_beneficio_anal_cosecha_id_94733c39_fk_cosechas_ FOREIGN KEY (cosecha_id)
    REFERENCES public.cosechas_cosecha (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS costo_beneficio_analisiscostobeneficio_cosecha_id_94733c39
    ON public.costo_beneficio_analisiscostobeneficio(cosecha_id);


ALTER TABLE IF EXISTS public.cultivos_cultivo
    ADD CONSTRAINT "cultivos_cultivo_Bancal_id_7546dd17_fk_bancal_bancal_id" FOREIGN KEY ("Bancal_id")
    REFERENCES public.bancal_bancal (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "cultivos_cultivo_Bancal_id_7546dd17"
    ON public.cultivos_cultivo("Bancal_id");


ALTER TABLE IF EXISTS public.cultivos_cultivo
    ADD CONSTRAINT "cultivos_cultivo_Especie_id_8ce56575_fk_especies_especie_id" FOREIGN KEY ("Especie_id")
    REFERENCES public.especies_especie (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "cultivos_cultivo_Especie_id_8ce56575"
    ON public.cultivos_cultivo("Especie_id");


ALTER TABLE IF EXISTS public.cultivos_cultivo
    ADD CONSTRAINT cultivos_cultivo_unidad_de_medida_id_7b31f66b_fk_unidad_me FOREIGN KEY (unidad_de_medida_id)
    REFERENCES public.unidad_medida_unidadmedida (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS cultivos_cultivo_unidad_de_medida_id_7b31f66b
    ON public.cultivos_cultivo(unidad_de_medida_id);


ALTER TABLE IF EXISTS public.datos_meteorologicos_datos_metereologicos
    ADD CONSTRAINT datos_meteorologicos_fk_bancal_id_02aa0f8d_fk_bancal_ba FOREIGN KEY (fk_bancal_id)
    REFERENCES public.bancal_bancal (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS datos_meteorologicos_datos_metereologicos_fk_bancal_id_02aa0f8d
    ON public.datos_meteorologicos_datos_metereologicos(fk_bancal_id);


ALTER TABLE IF EXISTS public.datos_meteorologicos_datos_metereologicos
    ADD CONSTRAINT datos_meteorologicos_fk_sensor_id_75d9072e_fk_sensores_ FOREIGN KEY (fk_sensor_id)
    REFERENCES public.sensores_sensor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS datos_meteorologicos_datos_metereologicos_fk_sensor_id_75d9072e
    ON public.datos_meteorologicos_datos_metereologicos(fk_sensor_id);


ALTER TABLE IF EXISTS public.datos_meteorologicos_datoshistoricos
    ADD CONSTRAINT datos_meteorologicos_fk_bancal_id_655c315c_fk_bancal_ba FOREIGN KEY (fk_bancal_id)
    REFERENCES public.bancal_bancal (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS datos_meteorologicos_datoshistoricos_fk_bancal_id_655c315c
    ON public.datos_meteorologicos_datoshistoricos(fk_bancal_id);


ALTER TABLE IF EXISTS public.datos_meteorologicos_datoshistoricos
    ADD CONSTRAINT datos_meteorologicos_fk_sensor_id_936cae87_fk_sensores_ FOREIGN KEY (fk_sensor_id)
    REFERENCES public.sensores_sensor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS datos_meteorologicos_datoshistoricos_fk_sensor_id_936cae87
    ON public.datos_meteorologicos_datoshistoricos(fk_sensor_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_content_type_id_c4bce8eb
    ON public.django_admin_log(content_type_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_usuarios_usuarios_id FOREIGN KEY (user_id)
    REFERENCES public.usuarios_usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_user_id_c564eba6
    ON public.django_admin_log(user_id);


ALTER TABLE IF EXISTS public.especies_especie
    ADD CONSTRAINT especies_especie_fk_tipo_especie_id_b0a0540b_fk_tipo_espe FOREIGN KEY (fk_tipo_especie_id)
    REFERENCES public.tipo_especies_tipoespecie (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS especies_especie_fk_tipo_especie_id_b0a0540b
    ON public.especies_especie(fk_tipo_especie_id);


ALTER TABLE IF EXISTS public.evapotranspiracion_evapotranspiracion
    ADD CONSTRAINT evapotranspiracion_e_fk_bancal_id_a0777635_fk_bancal_ba FOREIGN KEY (fk_bancal_id)
    REFERENCES public.bancal_bancal (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS evapotranspiracion_evapotranspiracion_fk_bancal_id_a0777635
    ON public.evapotranspiracion_evapotranspiracion(fk_bancal_id);


ALTER TABLE IF EXISTS public.insumos_insumo
    ADD CONSTRAINT insumos_insumo_tipo_insumo_id_56acb88c_fk_insumos_t FOREIGN KEY (tipo_insumo_id)
    REFERENCES public.insumos_tiposinsumo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS insumos_insumo_tipo_insumo_id_56acb88c
    ON public.insumos_insumo(tipo_insumo_id);


ALTER TABLE IF EXISTS public.insumos_insumo
    ADD CONSTRAINT insumos_insumo_unidad_medida_id_1734b98a_fk_unidad_me FOREIGN KEY (unidad_medida_id)
    REFERENCES public.unidad_medida_unidadmedida (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS insumos_insumo_unidad_medida_id_1734b98a
    ON public.insumos_insumo(unidad_medida_id);


ALTER TABLE IF EXISTS public.mapa_puntomapa
    ADD CONSTRAINT cultivo_mapa FOREIGN KEY (cultivo_id)
    REFERENCES public.cultivos_cultivo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.mapa_puntomapa
    ADD CONSTRAINT usuario_mapa FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios_usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pagos_pago
    ADD CONSTRAINT pagos_pago_salario_id_f61b0280_fk_salario_salario_id FOREIGN KEY (salario_id)
    REFERENCES public.salario_salario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS pagos_pago_salario_id_f61b0280
    ON public.pagos_pago(salario_id);


ALTER TABLE IF EXISTS public.pagos_pago
    ADD CONSTRAINT pagos_pago_usuario_id_b2dca9f3_fk_usuarios_usuarios_id FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios_usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS pagos_pago_usuario_id_b2dca9f3
    ON public.pagos_pago(usuario_id);


ALTER TABLE IF EXISTS public.pagos_pago_actividades
    ADD CONSTRAINT pagos_pago_actividad_actividad_id_9754ff4a_fk_actividad FOREIGN KEY (actividad_id)
    REFERENCES public.actividades_actividad (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS pagos_pago_actividades_actividad_id_9754ff4a
    ON public.pagos_pago_actividades(actividad_id);


ALTER TABLE IF EXISTS public.pagos_pago_actividades
    ADD CONSTRAINT pagos_pago_actividades_pago_id_a8e33af6_fk_pagos_pago_id FOREIGN KEY (pago_id)
    REFERENCES public.pagos_pago (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS pagos_pago_actividades_pago_id_a8e33af6
    ON public.pagos_pago_actividades(pago_id);


ALTER TABLE IF EXISTS public.plagas_plaga
    ADD CONSTRAINT plagas_plaga_fk_tipo_plaga_id_7abc3e50_fk_tipo_plag FOREIGN KEY (fk_tipo_plaga_id)
    REFERENCES public.tipo_plaga_tipoplaga (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS plagas_plaga_fk_tipo_plaga_id_7abc3e50
    ON public.plagas_plaga(fk_tipo_plaga_id);


ALTER TABLE IF EXISTS public.plantaciones_plantacion
    ADD CONSTRAINT plantaciones_plantac_id_cultivo_id_f443ea2b_fk_cultivos_ FOREIGN KEY (id_cultivo_id)
    REFERENCES public.cultivos_cultivo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS plantaciones_plantacion_id_cultivo_id_f443ea2b
    ON public.plantaciones_plantacion(id_cultivo_id);


ALTER TABLE IF EXISTS public.plantaciones_plantacion
    ADD CONSTRAINT plantaciones_plantacion_bancal_id_f422c01f_fk_bancal_bancal_id FOREIGN KEY (bancal_id)
    REFERENCES public.bancal_bancal (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS plantaciones_plantacion_bancal_id_f422c01f
    ON public.plantaciones_plantacion(bancal_id);


ALTER TABLE IF EXISTS public.precios_productos_precio_producto
    ADD CONSTRAINT "precio_producto_prec_Producto_id_0b0c51f4_fk_cosechas_" FOREIGN KEY ("Producto_id")
    REFERENCES public.cosechas_cosecha (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "precio_producto_precioproducto_Producto_id_0b0c51f4"
    ON public.precios_productos_precio_producto("Producto_id");


ALTER TABLE IF EXISTS public.precios_productos_precio_producto
    ADD CONSTRAINT precio_producto_prec_unidad_medida_id_9b402b80_fk_unidad_me FOREIGN KEY (unidad_medida_id)
    REFERENCES public.unidad_medida_unidadmedida (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS precios_productos_precio_producto_unidad_medida_id_c650f9e1
    ON public.precios_productos_precio_producto(unidad_medida_id);


ALTER TABLE IF EXISTS public.residuos_residuo
    ADD CONSTRAINT residuos_residuo_id_cosecha_id_7cd66f6f_fk_cosechas_cosecha_id FOREIGN KEY (id_cosecha_id)
    REFERENCES public.cosechas_cosecha (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS residuos_residuo_id_cosecha_id_7cd66f6f
    ON public.residuos_residuo(id_cosecha_id);


ALTER TABLE IF EXISTS public.residuos_residuo
    ADD CONSTRAINT residuos_residuo_id_tipo_residuo_id_242ace93_fk_tipos_res FOREIGN KEY (id_tipo_residuo_id)
    REFERENCES public.tipos_residuos_tiporesiduo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS residuos_residuo_id_tipo_residuo_id_242ace93
    ON public.residuos_residuo(id_tipo_residuo_id);


ALTER TABLE IF EXISTS public.salario_salario
    ADD CONSTRAINT salario_salario_rol_id_eb0fd81c_fk_roles_roles_id FOREIGN KEY (rol_id)
    REFERENCES public.roles_roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS salario_salario_rol_id_eb0fd81c
    ON public.salario_salario(rol_id);


ALTER TABLE IF EXISTS public.semillero_semillero
    ADD CONSTRAINT semillero_semillero_fk_especie_id_25546a35_fk_especies_ FOREIGN KEY (fk_especie_id)
    REFERENCES public.especies_especie (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS semillero_semillero_fk_especie_id_25546a35
    ON public.semillero_semillero(fk_especie_id);


ALTER TABLE IF EXISTS public.sensores_sensor
    ADD CONSTRAINT sensores_sensor_bancal_id_33135416_fk_bancal_bancal_id FOREIGN KEY (bancal_id)
    REFERENCES public.bancal_bancal (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS sensores_sensor_bancal_id_33135416
    ON public.sensores_sensor(bancal_id);


ALTER TABLE IF EXISTS public.sensores_sensor
    ADD CONSTRAINT sensores_sensor_tipo_sensor_id_9bf6198d_fk_sensores_ FOREIGN KEY (tipo_sensor_id)
    REFERENCES public.sensores_tiposensor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS sensores_sensor_tipo_sensor_id_9bf6198d
    ON public.sensores_sensor(tipo_sensor_id);


ALTER TABLE IF EXISTS public.usuarios_passwordresettoken
    ADD CONSTRAINT usuarios_passwordres_user_id_3c97028d_fk_usuarios_ FOREIGN KEY (user_id)
    REFERENCES public.usuarios_usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS usuarios_passwordresettoken_user_id_3c97028d
    ON public.usuarios_passwordresettoken(user_id);


ALTER TABLE IF EXISTS public.usuarios_usuarios
    ADD CONSTRAINT fk_rol_id FOREIGN KEY (rol_id)
    REFERENCES public.roles_roles (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS usuarios_usuarios_rol_id_120e55eb
    ON public.usuarios_usuarios(rol_id);


ALTER TABLE IF EXISTS public.usuarios_usuarios
    ADD CONSTRAINT usuarios_usuarios_rol_id_120e55eb_fk_roles_roles_id FOREIGN KEY (rol_id)
    REFERENCES public.roles_roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS usuarios_usuarios_rol_id_120e55eb
    ON public.usuarios_usuarios(rol_id);


ALTER TABLE IF EXISTS public.usuarios_usuarios_groups
    ADD CONSTRAINT usuarios_usuarios_gr_usuarios_id_65c166be_fk_usuarios_ FOREIGN KEY (usuarios_id)
    REFERENCES public.usuarios_usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS usuarios_usuarios_groups_usuarios_id_65c166be
    ON public.usuarios_usuarios_groups(usuarios_id);


ALTER TABLE IF EXISTS public.usuarios_usuarios_groups
    ADD CONSTRAINT usuarios_usuarios_groups_group_id_1e265f46_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS usuarios_usuarios_groups_group_id_1e265f46
    ON public.usuarios_usuarios_groups(group_id);


ALTER TABLE IF EXISTS public.usuarios_usuarios_user_permissions
    ADD CONSTRAINT usuarios_usuarios_us_permission_id_394f07a6_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS usuarios_usuarios_user_permissions_permission_id_394f07a6
    ON public.usuarios_usuarios_user_permissions(permission_id);


ALTER TABLE IF EXISTS public.usuarios_usuarios_user_permissions
    ADD CONSTRAINT usuarios_usuarios_us_usuarios_id_d860a7b5_fk_usuarios_ FOREIGN KEY (usuarios_id)
    REFERENCES public.usuarios_usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS usuarios_usuarios_user_permissions_usuarios_id_d860a7b5
    ON public.usuarios_usuarios_user_permissions(usuarios_id);


ALTER TABLE IF EXISTS public.venta_detalleventa
    ADD CONSTRAINT venta_detalleventa_producto_id_505fc25b_fk_precios_p FOREIGN KEY (producto_id)
    REFERENCES public.precios_productos_precio_producto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS venta_detalleventa_producto_id_505fc25b
    ON public.venta_detalleventa(producto_id);


ALTER TABLE IF EXISTS public.venta_detalleventa
    ADD CONSTRAINT venta_detalleventa_unidades_de_medida_i_9de20466_fk_unidad_me FOREIGN KEY (unidades_de_medida_id)
    REFERENCES public.unidad_medida_unidadmedida (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS venta_detalleventa_unidades_de_medida_id_9de20466
    ON public.venta_detalleventa(unidades_de_medida_id);


ALTER TABLE IF EXISTS public.venta_detalleventa
    ADD CONSTRAINT venta_detalleventa_venta_id_66610f20_fk_venta_venta_id FOREIGN KEY (venta_id)
    REFERENCES public.venta_venta (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS venta_detalleventa_venta_id_66610f20
    ON public.venta_detalleventa(venta_id);

END;